
test0: UContext_Test0.c UContext.c UContext.S
	gcc -g -Wall UContext_Test0.c UContext.c UContext.S

test1: UContext_Test1.c UContext.c UContext.S
	gcc -g -Wall -std=c99 UContext_Test1.c UContext.c UContext.S

clean:
	rm -rf a.out
